### ISSUE TITLE
May I ask if someone could get custom license?

### ISSUE THREAD

**Issue by cia48621793** [FWGS/xash3d#104]
I was trying to make a game with Xash3D. That however would take some modification to the engine(C++ wrapper, interface export, custom netcode, etc.), and I couldn't afford the price of GPLv3. I would like to ask if the original writer of the engine could issue me a custom license so I could go on working.

**Comment by a1batross** [comment]
I think, Xash3D is a nice engine to NOT make any changes inside it. 
Look at additional interfaces of Xash3D. It wasn't hard to use it. Physics, render, etc interfaces.

Anyway, I(or another contributors) can't give you permission to change license, because we are not authors of it. True author of Xash3D is Uncle Mike.

**Comment by cia48621793** [comment]
Well the very problem is, I have to share all my code with GPLv3, all my commitment. Not to tell me if I am going to expose my game protocol? That was a nasty question.

**Comment by a1batross** [comment]
If the problem in protocol, you can extend game protocol using custom messages. 

Look how it's working in Half-Life.
