### ISSUE TITLE
Gameplay between platforms, touch controls

### ISSUE THREAD

**Issue by ryan-sg** [FWGS/xash3d#165]
I have noticed, whilst playing some half-life deathmatch on the handful of servers out there, that I tend to be in the minority of players actually using a keyboard and mouse.

Many people are joining up with touch screen devices, and then I feel like an ogre stomping down on everyone that can't react as quickly.

To that end, has there been consideration of adding perhaps even just a server filter for touch controls players?  Maybe just an option to make a server touch-only or something... while having the option for them to still search all servers for a bigger challenge.

I suppose there must be some android devices out there that allow attaching an external keyboard/mouse, such as chromebooks?

**Comment by a1batross** [comment]
We have plans on it.

Filtering idea is nice, but here is some issues:
1) We don't have so many servers, so filtering will cause, for example,
empty server list for mouse users and many servers for touch users.
At this time, engine can receive input from four sources: keyboard, mouse,
touch and game controller.
Server's admin must declare allowed input sources?

2) Need some verification on a server, because relying on information got
from client is too "foolish".
Anyone who knows C language at basic level can build engine, that will send
fake information about input and it will ruin everything.
Server at this time knows only about "virtual" keys(IN_ATTACK, IN_JUMP,
etc) and actual view angles.


2016-08-17 23:33 GMT+06:00 ryan-sg <notifications@github.com>:

**Comment by a1batross** [comment]
Implemented by @mittorn. 

Server toggles accepted input devices with sv_allow_mouse, sv_allow_touch, sv_allow_joystick, sv_allow_vr cvars.
