### ISSUE TITLE
Players get stuck in floor bots or humans as more than 16 players join

### ISSUE THREAD

**Issue by ghost** [FWGS/xash3d#187]
![screenshot_20160916-002342](https://cloud.githubusercontent.com/assets/11255146/18575418/8cec37a0-7ba5-11e6-835f-5d560c6feb80.png)
![screenshot_20160916-001723](https://cloud.githubusercontent.com/assets/11255146/18575419/8cec8aca-7ba5-11e6-87d8-0530ff30cf20.png)
![screenshot_20160916-001545](https://cloud.githubusercontent.com/assets/11255146/18575420/8cf0155a-7ba5-11e6-8dd0-44fbdb547fb6.png)

**Comment by mittorn** [comment]
sv_unlag 0

**Comment by mittorn** [comment]
Please update your half-life server. Players cannot connect to it.

**Comment by a1batross** [comment]
It seems related with sv_unlag. I fixed it in latest development branch. 

Unlag is rewriting entvars_t::origin values, so when unlag tries to interpolate the positions between two frame it may cause that origin is outside the map. So there is SV_GetTrueOrigin function, which is should return non-interpolated origin, so collision will not be a messed. The bug was in this function, because it returned non-"true" values.
