### ISSUE TITLE
Crash (CS 1.6 Client)

### ISSUE THREAD

**Issue by chinelosabio** [FWGS/xash3d#256]
CS 1.6 Client crashs every 10 minutes of gameplay on original maps without custom skins/mods/decals/textures.
Please help! I don't know why this is happening...
Sorry for bad english.

**Comment by a1batross** [comment]
This caused by ReGameDLL update which is used undocumented feature of GoldSource engine and which is not implemented properly in Xash3D. 

Fix was pushed and will arrive in 0.19.1 update.

At this moment, you can grab testing version from https://github.com/FWGS/xash3d-deploy/tree/travis-0.19.x. Just download APK file, install it and run CS16Client with Xash3D (test).
