### ISSUE TITLE
iOS: HD textures (.tga) displaying the wrong way round

### ISSUE THREAD

**Issue by CyanFireUK** [FWGS/xash3d#399]
After adding HD textures to my iOS setup when i play the game the textures are flipped and are displaying the wrong way round. Any way to fix this issue?

**Comment by nekonomicon** [comment]
May be HD textures was created with wrong orientation(bottom-left)?

**Comment by a1batross** [comment]
Itself, there is two ways of using external textures.
First one, is using as detail textures. This method is used in GoldSrc, but in Xash detail texture implementation is completely different, so it will not work properly. Maybe it will be fixed in new engine.
Second one is Xash extension -- materials. However, it's future is not bright, it was removed in new engine by Unkle Mike and I don't know should we restore it in fork.

**Comment by CyanFireUK** [comment]
nekonomicon was right, the textures were the wrong orientation, i never looked at the .tga files before. Batch flipped them and all is good!
